# Dependencies
#markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Binayak Dasgupta
tagline:          'Coder at work'
description:      'Newbi stuggeling through programming and data science.'
url:              https://binayakd.github.io/
baseurl:          /

author:
  name:           'Binayak Dasgupta'
  url:            https://binayakd.github.io/

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/binayakd

gems: [jekyll-paginate]
