# Dependencies
#markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Binayak Dasgupta
tagline:          'Jack of some trades, master of None'
description:      ''
url:              'https://binayakd.github.io/'
baseurl:          '/'

author:
  name:           'Binayak Dasgupta'
  url:            https://binayakd.github.io/

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/binayakd

plugins: 
  - jekyll-paginate
  - jekyll-archives

jekyll-archives:
  enabled: all
  layout: post

#theme: jekyll-theme-minimal
